import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="bg-white border-b border-gray-100 py-4 px-6 flex gap-6 justify-center sticky top-0 z-50 shadow-sm">
          <Link href="/" className="font-bold text-gray-700 hover:text-blue-600 transition-colors">📊 Dashboard</Link>
          <Link href="/task-1" className="font-bold text-gray-700 hover:text-blue-600 transition-colors">🚀 Task 1 UI</Link>
          <Link href="/task-2-ui" className="font-bold text-gray-700 hover:text-blue-600 transition-colors">🔥 Task 2 UI</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
